INSERT INTO student (name, birthday, groupnumber)
VALUES ('John', '2009-02-01', 1),
       ('Chris', '2009-03-15', 1),
       ('Carl', '2009-05-23', 1),
       ('Oliver', '2008-07-05', 2),
       ('James', '2008-08-21', 2),
       ('Lucas', '2008-10-11', 2),
       ('Henry', '2007-12-03', 2),
       ('Jacob', '2007-09-20', 3),
       ('Logan', '2007-11-29', 3),
       ('Sarah', '2006-03-14', 4),
       ('Emily', '2006-06-30', 4),
       ('Isabella', '2006-08-12', 4),
       ('Michael', '2005-02-09', 5),
       ('William', '2005-05-27', 5),
       ('Ethan', '2005-09-12', 5);

INSERT INTO subject (name, description, grade)
VALUES ('Art', 'Art subject for 1st grade', 1),
       ('Music', 'Music subject for 1st grade', 1),
       ('Geography', 'Geography subject for 2nd grade', 2),
       ('History', 'History subject for 2nd grade', 2),
       ('PE', 'Physical Education subject for 3rd grade', 3),
       ('Math', 'Math subject for 3rd grade', 3),
       ('Science', 'Science subject for 4th grade', 4),
       ('IT', 'IT subject for 4th grade', 4),
       ('Chemistry', 'Biology subject for 5th grade', 5),
       ('Biology', 'Chemistry subject for 5th grade', 5);

INSERT INTO paymenttype (name)
VALUES ('DAILY'),
       ('WEEKLY'),
       ('MONTHLY');

INSERT INTO payment (type_id, amount, student_id)
VALUES ((SELECT id FROM paymenttype WHERE name = 'WEEKLY'),
        50.0,
        (SELECT id FROM student WHERE name = 'John' AND grade = 1)),
       ((SELECT id FROM paymenttype WHERE name = 'MONTHLY'),
        100.0,
        (SELECT id FROM student WHERE name = 'Oliver' AND grade = 2)),
       ((SELECT id FROM paymenttype WHERE name = 'WEEKLY'),
        60.0,
        (SELECT id FROM student WHERE name = 'Henry' AND grade = 2)),
       ((SELECT id FROM paymenttype WHERE name = 'DAILY'),
        10.0,
        (SELECT id FROM student WHERE name = 'James' AND grade = 2)) );


INSERT INTO mark (student_id, subject_id, mark)
VALUES ((SELECT id FROM student WHERE name = 'Chris' AND grade = 1),
        (SELECT id FROM subject WHERE name = 'Art'),
        8),
       ((SELECT id FROM student WHERE name = 'Oliver' AND grade = 2),
        (SELECT id FROM subject WHERE name = 'History'),
        5),
       ((SELECT id FROM student WHERE name = 'James' AND grade = 2),
        (SELECT id FROM subject WHERE name = 'Geography'),
        9),
       ((SELECT id FROM student WHERE name = 'Jacob' AND grade = 3),
        (SELECT id FROM subject WHERE name = 'Math'),
        4),
       ((SELECT id FROM student WHERE name = 'Logan' AND grade = 3),
        (SELECT id FROM subject WHERE name = 'PE'),
        9),
       ((SELECT id FROM student WHERE name = 'Carl' AND grade = 1),
        (SELECT id FROM subject WHERE name = 'Music'),
        7),
       ((SELECT id FROM student WHERE name = 'Henry' AND grade = 2),
        (SELECT id FROM subject WHERE name = 'Geography'),
        6),
       ((SELECT id FROM student WHERE name = 'Lucas' AND grade = 2),
        (SELECT id FROM subject WHERE name = 'History'),
        7),
       ((SELECT id FROM student WHERE name = 'Jacob' AND grade = 3),
        (SELECT id FROM subject WHERE name = 'PE'),
        8),
       ((SELECT id FROM student WHERE name = 'Logan' AND grade = 3),
        (SELECT id FROM subject WHERE name = 'Math'),
        7),
       ((SELECT id FROM student WHERE name = 'John' AND grade = 1),
        (SELECT id FROM subject WHERE name = 'Art'),
        6),
       ((SELECT id FROM student WHERE name = 'Oliver' AND grade = 2),
        (SELECT id FROM subject WHERE name = 'Science'),
        8),
       ((SELECT id FROM student WHERE name = 'James' AND grade = 2),
        (SELECT id FROM subject WHERE name = 'IT'),
        7),
       ((SELECT id FROM student WHERE name = 'Jacob' AND grade = 3),
        (SELECT id FROM subject WHERE name = 'Science'),
        6),
       ((SELECT id FROM student WHERE name = 'Logan' AND grade = 3),
        (SELECT id FROM subject WHERE name = 'IT'),
        7);