ALTER TABLE student MODIFY COLUMN birthday DATE NOT NULL;

ALTER TABLE mark MODIFY COLUMN mark INT(2) NOT NULL CHECK (mark BETWEEN 1 AND 10);
ALTER TABLE mark MODIFY COLUMN student_id INT(11) NOT NULL;
ALTER TABLE mark MODIFY COLUMN subject_id INT(11) NOT NULL;

ALTER TABLE subject MODIFY COLUMN grade INT(1) NOT NULL CHECK (grade BETWEEN 1 AND 5);

ALTER TABLE paymenttype ADD UNIQUE(name);

ALTER TABLE payment MODIFY COLUMN type_id INT(11) NOT NULL;
ALTER TABLE payment MODIFY COLUMN amount DECIMAL(10,2) NOT NULL;
ALTER TABLE payment MODIFY COLUMN payment_date DATETIME NOT NULL;
